### ISSUE TITLE
`errorOnInconsistentLocale` option behavior with out-of-sync translations

### ISSUE THREAD

**Issue by HiDeoo** [HiDeoo/starlight-links-validator#25]
This issue is a discussion following up the potential usage of the plugin in the Starlight documentation.

The configuration in the Starlight documentation would be the following:

```js
starlightLinksValidator({
  errorOnFallbackPages: false,
  errorOnInconsistentLocale: true,
  errorOnRelativeLinks: false,
});
```

At the moment, using the plugin with this configuration would result in 5 errors which are all identical but I'm not sure what is the expected behavior in this case as this is not one I personally encountered before. Imagine the following scenario in the Starlight documentation:

- `Person A` translates the configuration reference in language `yy`.
- `Person B` adds a feature with a new section in the configuration reference.
- `Person C` adds a feature with a new documentation page which contains a link to the new section previously added by `Person B`, e.g. `/reference/configuration/#new-section`
- `Person D` translates the new page added by `Person C` in language `yy`.

In this scenario, the link that `Person D` would add in the translated page would be `/yy/reference/configuration/#new-section` with the `errorOnInconsistentLocale` option set to `true` but this would result in an error as the configuration page has not been updated yet in language `yy` and does not contain the new section.

I'm not sure what is the expected behavior in this case.

cc @delucis

**Comment by delucis** [comment]
If I understood correctly (which is not guaranteed, because there’s a lot of steps here 😅), I believe there should indeed be an error after bullet 4 unless the PR also updates the configuration reference translation — after all, there is a broken link we need to report.

We do exactly this in the Astro docs and while sometimes annoying — it can force translations to happen in a specific order — I think any other solution is also suboptimal. It means either having a) a broken fragment link (`/yy/reference/configuration/#new-section` doesn’t exist yet, but we link to it) or b) a link to a different locale (we link to `/reference/configuration/#new-section` instead, which exists but takes the user out of their preferred locale).

Admittedly, this does make non-greenfield adoption trickier — you may need to make significant translation changes before a link checker can pass — so making this configurable does still make sense to me. Maybe as an opt-out if you’re stuck?

**Comment by HiDeoo** [comment]
You understood correctly, sorry, it was maybe not the best example ^^

> We do exactly this in the Astro docs and while sometimes annoying — it can force translations to happen in a specific order — I think any other solution is also suboptimal.

Oh, then I think we totally agree but for some reason, I was under the impression that forcing some order to ensure always valid links was not something desirable for the Starlight Docs.

Then, I think this is a non-issue and we can close this, and when we get to a relatively small number of i18n PRs in the Starlight Docs, I think we should be able to make a PR to enable this plugin.
