### ISSUE TITLE
Support external links

### ISSUE THREAD

**Issue by dsalaza4** [HiDeoo/starlight-links-validator#51]
### Is your feature request related to a problem?

Hey, It would be great if this tool also checked the HTTP codes for each external link referenced.

### Describe the solution you'd like

Support a `validateExternalLinks` option and set it to `false` by default. 

Users should be able to set it to true in order to validate external links.

This could be done by sending a simple request to each url and see the HTTP response code. If it is 404, then fail.

**Comment by HiDeoo** [comment]
Thanks for your feedkback :raised_hands:

This plugin was designed from the ground up to only validate internal links with additional rules specific to Starlight regarding i18n, fallback pages, etc. Validation of external links is not something I am planning to support in this plugin due to how fragile it can be and also of the additional complexity it would add to the plugin.

For this kind of usage, I think something like [lychee](https://lychee.cli.rs/) would be a better fit.
